-- MangaWhisper database schema.
-- This file is the single source of truth for the schema (no EF migrations).
-- Both MangaWhisper.Api and MangaWhisper.BackgroundWorker map their entities onto these tables.
--
-- Postgres runs the scripts in /docker-entrypoint-initdb.d only when the data volume is empty.
-- To re-create the database from scratch: docker compose down -v && docker compose up

-- ---------------------------------------------------------------------------
-- Domain tables
-- ---------------------------------------------------------------------------

CREATE TABLE "Mangas" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title"         character varying(255) NOT NULL,
    "CoverImageUrl" character varying(500) NOT NULL DEFAULT '',
    "Status"        integer NOT NULL,
    "CreatedAt"     timestamp with time zone NOT NULL,
    "UpdatedAt"     timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX "IX_Mangas_Title" ON "Mangas" ("Title");

CREATE TABLE "MangaCheckers" (
    "Id"                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MangaId"              integer NOT NULL REFERENCES "Mangas" ("Id") ON DELETE CASCADE,
    "LastKnownChapter"     integer NOT NULL,
    "CheckIntervalMinutes" integer NOT NULL,
    "IsActive"             boolean NOT NULL,
    "CheckerStatus"        integer NOT NULL,
    "LastCheckedAt"        timestamp with time zone NULL,
    "CreatedAt"            timestamp with time zone NOT NULL,
    "SiteIdentifier"       character varying(100) NOT NULL
);

CREATE INDEX "IX_MangaCheckers_MangaId" ON "MangaCheckers" ("MangaId");

CREATE TABLE "Chapters" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MangaId"     integer NOT NULL REFERENCES "Mangas" ("Id") ON DELETE CASCADE,
    "Number"      integer NOT NULL,
    "Title"       character varying(255) NOT NULL,
    "Url"         character varying(500) NOT NULL,
    "ExtractedAt" timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX "IX_Chapters_MangaId_Number" ON "Chapters" ("MangaId", "Number");

-- ---------------------------------------------------------------------------
-- ASP.NET Core Identity tables (used only by MangaWhisper.Api)
-- ---------------------------------------------------------------------------

CREATE TABLE "AspNetRoles" (
    "Id"               text PRIMARY KEY,
    "Name"             character varying(256) NULL,
    "NormalizedName"   character varying(256) NULL,
    "ConcurrencyStamp" text NULL
);

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE TABLE "AspNetUsers" (
    "Id"                   text PRIMARY KEY,
    "FullName"             text NULL,
    "CreatedAt"            timestamp with time zone NOT NULL,
    "UserName"             character varying(256) NULL,
    "NormalizedUserName"   character varying(256) NULL,
    "Email"                character varying(256) NULL,
    "NormalizedEmail"      character varying(256) NULL,
    "EmailConfirmed"       boolean NOT NULL,
    "PasswordHash"         text NULL,
    "SecurityStamp"        text NULL,
    "ConcurrencyStamp"     text NULL,
    "PhoneNumber"          text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled"     boolean NOT NULL,
    "LockoutEnd"           timestamp with time zone NULL,
    "LockoutEnabled"       boolean NOT NULL,
    "AccessFailedCount"    integer NOT NULL
);

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE TABLE "AspNetRoleClaims" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RoleId"     text NOT NULL REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    "ClaimType"  text NULL,
    "ClaimValue" text NULL
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE TABLE "AspNetUserClaims" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"     text NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    "ClaimType"  text NULL,
    "ClaimValue" text NULL
);

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider"       text NOT NULL,
    "ProviderKey"         text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId"              text NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    PRIMARY KEY ("LoginProvider", "ProviderKey")
);

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    "RoleId" text NOT NULL REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    PRIMARY KEY ("UserId", "RoleId")
);

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE TABLE "AspNetUserTokens" (
    "UserId"        text NOT NULL REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    "LoginProvider" text NOT NULL,
    "Name"          text NOT NULL,
    "Value"         text NULL,
    PRIMARY KEY ("UserId", "LoginProvider", "Name")
);
